### ISSUE TITLE
Norwegian UI and descriptions on login page

### ISSUE THREAD

**Issue by mchyll** [tihlde/CaptivePortal#2]
- Change UI to Norsk?

- Add some more descriptions on the login page, à la: "Velkommen til TIHLDE LAN! Vennligst logg inn med din Colargolbruker, eller kjøp en gjestebruker. Kontakt Drift dersom du ikke husker passordet ditt". On successful login: "Du har nå internettilgang, happy gaming!" etc.

**Comment by bjornkpu** [comment]
Ah, smart. All for it. it's primarily for internal use.

**Comment by bjornkpu** [comment]
Sånn ^_^ likte det bedre. la bare inn forslaget ditt, så endre vi det om vi finn på nåkka bedre :)

**Comment by bjornkpu** [comment]
Vent, skal vi gjøre innputfeltan norsk? og Sign in -> Logg inn  ?

**Comment by mchyll** [comment]
Ja, tenkte vi kan gjøre hele UI'et norsk, med knapper og alt, så får det et mer helhetlig preg 🙂 Jeg fikser det nå, så ser vi an hva vi synes om det
